import * as anchor from '@coral-xyz/anchor';
import { Program } from '@coral-xyz/anchor';
import {
  Keypair,
  PublicKey,
  SystemProgram,
  Transaction,
  TransactionInstruction,
  SYSVAR_INSTRUCTIONS_PUBKEY,
} from '@solana/web3.js';
import {
  createMint,
  createAssociatedTokenAccount,
  mintTo,
  getAssociatedTokenAddress,
  getAccount,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from '@solana/spl-token';
import * as nacl from 'tweetnacl';
import { serialize } from 'borsh';
import { expect } from 'chai';

// Type stub — will be generated by anchor build
type PropsimVault = any;

describe('propsim_vault', () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.PropsimVault as Program<PropsimVault>;
  const authority = provider.wallet as anchor.Wallet;

  let usdcMint: PublicKey;
  let configPda: PublicKey;
  let configBump: number;
  let vaultAuthority: PublicKey;
  let vaultAuthorityBump: number;
  let vaultUsdc: PublicKey;

  // Test claim signer (Ed25519 keypair)
  const claimSigner = nacl.sign.keyPair();
  const claimSignerPubkey = new PublicKey(claimSigner.publicKey);

  const domain = Buffer.alloc(16, 0);
  Buffer.from('PROPSIM_PAYOUT_V', 'utf8').copy(domain, 0, 0, 16);
  const domainArray = Array.from(domain) as number[];

  const userKeypair = Keypair.generate();
  let userUsdc: PublicKey;

  const DAILY_CAP = new anchor.BN(5000_000_000); // 5000 USDC (6 decimals)

  before(async () => {
    // Airdrop to user
    const sig = await provider.connection.requestAirdrop(
      userKeypair.publicKey,
      10 * anchor.web3.LAMPORTS_PER_SOL,
    );
    await provider.connection.confirmTransaction(sig);

    // Create USDC mint
    usdcMint = await createMint(
      provider.connection,
      (authority as any).payer,
      authority.publicKey,
      null,
      6,
    );

    // Derive PDAs
    [configPda, configBump] = PublicKey.findProgramAddressSync(
      [Buffer.from('config'), authority.publicKey.toBuffer()],
      program.programId,
    );

    [vaultAuthority, vaultAuthorityBump] = PublicKey.findProgramAddressSync(
      [Buffer.from('vault'), configPda.toBuffer()],
      program.programId,
    );

    vaultUsdc = await getAssociatedTokenAddress(usdcMint, vaultAuthority, true);
  });

  it('initializes config', async () => {
    await program.methods
      .initializeConfig(
        claimSignerPubkey,
        usdcMint,
        true,
        DAILY_CAP,
        domainArray,
      )
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const config = await program.account.vaultConfig.fetch(configPda);
    expect(config.authority.toBase58()).to.equal(authority.publicKey.toBase58());
    expect(config.propsimSigner.toBase58()).to.equal(claimSignerPubkey.toBase58());
    expect(config.enableDailyCap).to.be.true;
    expect(config.version).to.equal(1);
  });

  it('initializes vault', async () => {
    await program.methods
      .initializeVault()
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        vaultAuthority,
        vaultUsdc,
        usdcMint,
        systemProgram: SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .rpc();

    // Verify vault USDC account exists
    const vaultAccount = await getAccount(provider.connection, vaultUsdc);
    expect(vaultAccount.owner.toBase58()).to.equal(vaultAuthority.toBase58());
  });

  it('funds vault with USDC', async () => {
    // Mint USDC to the vault
    await mintTo(
      provider.connection,
      (authority as any).payer,
      usdcMint,
      vaultUsdc,
      authority.publicKey,
      100_000_000_000, // 100,000 USDC
    );

    const vaultAccount = await getAccount(provider.connection, vaultUsdc);
    expect(Number(vaultAccount.amount)).to.equal(100_000_000_000);
  });

  it('redeems a valid claim', async () => {
    // Create user USDC ATA
    userUsdc = await createAssociatedTokenAccount(
      provider.connection,
      (authority as any).payer,
      usdcMint,
      userKeypair.publicKey,
    );

    const amount = new anchor.BN(1000_000_000); // 1000 USDC
    const nowUnix = Math.floor(Date.now() / 1000);
    const dayId = Math.floor(Date.now() / (86400 * 1000));

    // Build claim ID (32 bytes)
    const crypto = require('crypto');
    const claimId = crypto.createHash('sha256')
      .update(`test_claim_1`)
      .digest();

    // Build ClaimV1 bytes (Borsh serialization matching on-chain struct)
    const claimV1Schema = {
      struct: {
        version: 'u8',
        domain: { array: { type: 'u8', len: 16 } },
        program_id: { array: { type: 'u8', len: 32 } },
        config: { array: { type: 'u8', len: 32 } },
        claim_id: { array: { type: 'u8', len: 32 } },
        user: { array: { type: 'u8', len: 32 } },
        usdc_mint: { array: { type: 'u8', len: 32 } },
        amount: 'u64',
        valid_after: 'i64',
        valid_before: 'i64',
        day_id: 'u32',
        daily_cap: 'u64',
      },
    };

    const claimData = {
      version: 1,
      domain: Array.from(domain),
      program_id: Array.from(program.programId.toBytes()),
      config: Array.from(configPda.toBytes()),
      claim_id: Array.from(claimId),
      user: Array.from(userKeypair.publicKey.toBytes()),
      usdc_mint: Array.from(usdcMint.toBytes()),
      amount: BigInt(amount.toString()),
      valid_after: BigInt(nowUnix - 120),
      valid_before: BigInt(nowUnix + 600),
      day_id: dayId,
      daily_cap: BigInt(DAILY_CAP.toString()),
    };

    const messageBytes = Buffer.from(serialize(claimV1Schema, claimData));
    const signature = nacl.sign.detached(messageBytes, claimSigner.secretKey);

    // Build Ed25519 verify instruction
    const ed25519Ix = buildEd25519Ix(
      Buffer.from(claimSigner.publicKey),
      messageBytes,
      Buffer.from(signature),
    );

    // Derive ClaimMarker PDA
    const [claimMarker] = PublicKey.findProgramAddressSync(
      [Buffer.from('claim'), configPda.toBuffer(), claimId],
      program.programId,
    );

    // Derive UserDay PDA
    const dayBuf = Buffer.alloc(4);
    dayBuf.writeUInt32LE(dayId, 0);
    const [userDay] = PublicKey.findProgramAddressSync(
      [Buffer.from('day'), configPda.toBuffer(), userKeypair.publicKey.toBuffer(), dayBuf],
      program.programId,
    );

    // Build redeem instruction via Anchor
    const redeemIx = await program.methods
      .redeemClaim(
        {
          version: 1,
          domain: domainArray,
          programId: program.programId,
          config: configPda,
          claimId: Array.from(claimId),
          user: userKeypair.publicKey,
          usdcMint,
          amount,
          validAfter: new anchor.BN(nowUnix - 120),
          validBefore: new anchor.BN(nowUnix + 600),
          dayId,
          dailyCap: DAILY_CAP,
        },
        Array.from(signature),
      )
      .accounts({
        config: configPda,
        vaultAuthority,
        vaultUsdc,
        user: userKeypair.publicKey,
        userUsdc,
        usdcMint,
        claimMarker,
        userDay,
        instructionsSysvar: SYSVAR_INSTRUCTIONS_PUBKEY,
        tokenProgram: TOKEN_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .instruction();

    // Build tx: ed25519_ix then redeem_ix
    const tx = new Transaction();
    tx.add(ed25519Ix);
    tx.add(redeemIx);

    await provider.sendAndConfirm(tx, [userKeypair]);

    // Verify user received USDC
    const userAccount = await getAccount(provider.connection, userUsdc);
    expect(Number(userAccount.amount)).to.equal(1000_000_000);

    // Verify claim marker
    const marker = await program.account.claimMarker.fetch(claimMarker);
    expect(marker.used).to.be.true;
    expect(marker.user.toBase58()).to.equal(userKeypair.publicKey.toBase58());
  });

  it('rejects replay of the same claim', async () => {
    const amount = new anchor.BN(1000_000_000);
    const nowUnix = Math.floor(Date.now() / 1000);
    const dayId = Math.floor(Date.now() / (86400 * 1000));

    const crypto = require('crypto');
    const claimId = crypto.createHash('sha256').update('test_claim_1').digest();

    const claimV1Schema = {
      struct: {
        version: 'u8',
        domain: { array: { type: 'u8', len: 16 } },
        program_id: { array: { type: 'u8', len: 32 } },
        config: { array: { type: 'u8', len: 32 } },
        claim_id: { array: { type: 'u8', len: 32 } },
        user: { array: { type: 'u8', len: 32 } },
        usdc_mint: { array: { type: 'u8', len: 32 } },
        amount: 'u64',
        valid_after: 'i64',
        valid_before: 'i64',
        day_id: 'u32',
        daily_cap: 'u64',
      },
    };

    const claimData = {
      version: 1,
      domain: Array.from(domain),
      program_id: Array.from(program.programId.toBytes()),
      config: Array.from(configPda.toBytes()),
      claim_id: Array.from(claimId),
      user: Array.from(userKeypair.publicKey.toBytes()),
      usdc_mint: Array.from(usdcMint.toBytes()),
      amount: BigInt(amount.toString()),
      valid_after: BigInt(nowUnix - 120),
      valid_before: BigInt(nowUnix + 600),
      day_id: dayId,
      daily_cap: BigInt(DAILY_CAP.toString()),
    };

    const messageBytes = Buffer.from(serialize(claimV1Schema, claimData));
    const signature = nacl.sign.detached(messageBytes, claimSigner.secretKey);

    const ed25519Ix = buildEd25519Ix(
      Buffer.from(claimSigner.publicKey),
      messageBytes,
      Buffer.from(signature),
    );

    const [claimMarker] = PublicKey.findProgramAddressSync(
      [Buffer.from('claim'), configPda.toBuffer(), claimId],
      program.programId,
    );

    const dayBuf = Buffer.alloc(4);
    dayBuf.writeUInt32LE(dayId, 0);
    const [userDay] = PublicKey.findProgramAddressSync(
      [Buffer.from('day'), configPda.toBuffer(), userKeypair.publicKey.toBuffer(), dayBuf],
      program.programId,
    );

    try {
      const redeemIx = await program.methods
        .redeemClaim(
          {
            version: 1,
            domain: domainArray,
            programId: program.programId,
            config: configPda,
            claimId: Array.from(claimId),
            user: userKeypair.publicKey,
            usdcMint,
            amount,
            validAfter: new anchor.BN(nowUnix - 120),
            validBefore: new anchor.BN(nowUnix + 600),
            dayId,
            dailyCap: DAILY_CAP,
          },
          Array.from(signature),
        )
        .accounts({
          config: configPda,
          vaultAuthority,
          vaultUsdc,
          user: userKeypair.publicKey,
          userUsdc,
          usdcMint,
          claimMarker,
          userDay,
          instructionsSysvar: SYSVAR_INSTRUCTIONS_PUBKEY,
          tokenProgram: TOKEN_PROGRAM_ID,
          associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
        })
        .instruction();

      const tx = new Transaction();
      tx.add(ed25519Ix);
      tx.add(redeemIx);

      await provider.sendAndConfirm(tx, [userKeypair]);
      expect.fail('Should have thrown — claim already used');
    } catch (err: any) {
      // ClaimMarker account already exists (init constraint fails)
      expect(err).to.exist;
    }
  });

  it('enforces daily cap', async () => {
    const amount = new anchor.BN(4500_000_000); // 4500 USDC — total would be 5500, over 5000 cap
    const nowUnix = Math.floor(Date.now() / 1000);
    const dayId = Math.floor(Date.now() / (86400 * 1000));

    const crypto = require('crypto');
    const claimId = crypto.createHash('sha256').update('test_claim_2_overcap').digest();

    const claimV1Schema = {
      struct: {
        version: 'u8',
        domain: { array: { type: 'u8', len: 16 } },
        program_id: { array: { type: 'u8', len: 32 } },
        config: { array: { type: 'u8', len: 32 } },
        claim_id: { array: { type: 'u8', len: 32 } },
        user: { array: { type: 'u8', len: 32 } },
        usdc_mint: { array: { type: 'u8', len: 32 } },
        amount: 'u64',
        valid_after: 'i64',
        valid_before: 'i64',
        day_id: 'u32',
        daily_cap: 'u64',
      },
    };

    const claimData = {
      version: 1,
      domain: Array.from(domain),
      program_id: Array.from(program.programId.toBytes()),
      config: Array.from(configPda.toBytes()),
      claim_id: Array.from(claimId),
      user: Array.from(userKeypair.publicKey.toBytes()),
      usdc_mint: Array.from(usdcMint.toBytes()),
      amount: BigInt(amount.toString()),
      valid_after: BigInt(nowUnix - 120),
      valid_before: BigInt(nowUnix + 600),
      day_id: dayId,
      daily_cap: BigInt(DAILY_CAP.toString()),
    };

    const messageBytes = Buffer.from(serialize(claimV1Schema, claimData));
    const signature = nacl.sign.detached(messageBytes, claimSigner.secretKey);

    const ed25519Ix = buildEd25519Ix(
      Buffer.from(claimSigner.publicKey),
      messageBytes,
      Buffer.from(signature),
    );

    const [claimMarker] = PublicKey.findProgramAddressSync(
      [Buffer.from('claim'), configPda.toBuffer(), claimId],
      program.programId,
    );

    const dayBuf = Buffer.alloc(4);
    dayBuf.writeUInt32LE(dayId, 0);
    const [userDay] = PublicKey.findProgramAddressSync(
      [Buffer.from('day'), configPda.toBuffer(), userKeypair.publicKey.toBuffer(), dayBuf],
      program.programId,
    );

    try {
      const redeemIx = await program.methods
        .redeemClaim(
          {
            version: 1,
            domain: domainArray,
            programId: program.programId,
            config: configPda,
            claimId: Array.from(claimId),
            user: userKeypair.publicKey,
            usdcMint,
            amount,
            validAfter: new anchor.BN(nowUnix - 120),
            validBefore: new anchor.BN(nowUnix + 600),
            dayId,
            dailyCap: DAILY_CAP,
          },
          Array.from(signature),
        )
        .accounts({
          config: configPda,
          vaultAuthority,
          vaultUsdc,
          user: userKeypair.publicKey,
          userUsdc,
          usdcMint,
          claimMarker,
          userDay,
          instructionsSysvar: SYSVAR_INSTRUCTIONS_PUBKEY,
          tokenProgram: TOKEN_PROGRAM_ID,
          associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
        })
        .instruction();

      const tx = new Transaction();
      tx.add(ed25519Ix);
      tx.add(redeemIx);

      await provider.sendAndConfirm(tx, [userKeypair]);
      expect.fail('Should have thrown — daily cap exceeded');
    } catch (err: any) {
      expect(err.toString()).to.include('DailyCapExceeded');
    }
  });

  it('updates propsim signer (authority only)', async () => {
    const newSigner = Keypair.generate();

    await program.methods
      .setPropsimSigner(newSigner.publicKey)
      .accounts({
        authority: authority.publicKey,
        config: configPda,
      })
      .rpc();

    const config = await program.account.vaultConfig.fetch(configPda);
    expect(config.propsimSigner.toBase58()).to.equal(newSigner.publicKey.toBase58());

    // Restore original signer for other tests
    await program.methods
      .setPropsimSigner(claimSignerPubkey)
      .accounts({
        authority: authority.publicKey,
        config: configPda,
      })
      .rpc();
  });

  it('updates daily cap settings', async () => {
    await program.methods
      .setDailyCap(false, new anchor.BN(10000_000_000))
      .accounts({
        authority: authority.publicKey,
        config: configPda,
      })
      .rpc();

    const config = await program.account.vaultConfig.fetch(configPda);
    expect(config.enableDailyCap).to.be.false;
    expect(config.dailyCapUsdc.toNumber()).to.equal(10000_000_000);
  });
});

/**
 * Build an Ed25519 program instruction for signature verification.
 */
function buildEd25519Ix(
  pubkey: Buffer,
  message: Buffer,
  signature: Buffer,
): TransactionInstruction {
  const ED25519_PROGRAM_ID = new PublicKey('Ed25519SigVerify111111111111111111111111111');

  const numSignatures = 1;
  const pubkeyOffset = 16;
  const signatureOffset = 48;
  const messageOffset = 112;
  const messageSize = message.length;

  const dataLen = messageOffset + messageSize;
  const data = Buffer.alloc(dataLen);

  data.writeUInt16LE(numSignatures, 0);
  data.writeUInt16LE(0, 2); // padding

  // Signature offsets struct
  data.writeUInt16LE(signatureOffset, 4);
  data.writeUInt16LE(0xffff, 6);
  data.writeUInt16LE(pubkeyOffset, 8);
  data.writeUInt16LE(0xffff, 10);
  data.writeUInt16LE(messageOffset, 12);
  data.writeUInt16LE(messageSize, 14);

  pubkey.copy(data, pubkeyOffset);
  signature.copy(data, signatureOffset);
  message.copy(data, messageOffset);

  return new TransactionInstruction({
    keys: [],
    programId: ED25519_PROGRAM_ID,
    data,
  });
}
